version: '3'

services:
    solr:
        image: solr:6.6.0
        hostname: solr
        ports:
            - 8983:8983
        volumes:
            - ./generated_solr_core:/tmp/reactome-core:rw
            - ./logs/solr/:/opt/solr/server/logs/
            - ../solr/data/solr_data/reactome/conf:/tmp/reactome-solr-conf
            - ../solr/solr_init.sh:/solr_init.sh
        entrypoint: /bin/bash /solr_init.sh /tmp/reactome-solr-conf reactome
        networks:
            - solr-index-builder

    neo4j:
        image: neo4j
        hostname: neo4j
        env_file:
            - neo4j.env
        volumes:
            - ../neo4j/data:/var/lib/neo4j/data/databases
            - ../neo4j/neo4j-init.sh:/data/neo4j-init.sh
            - ../neo4j/conf/:/var/lib/neo4j/conf/
            - ./logs/neo4j/:/var/lib/neo4j/logs/
        ports:
            - 7474:7474
            - 7687:7687
        networks:
            - solr-index-builder

networks:
    solr-index-builder:
        driver: bridge
