version: '3'
services:

  tomcat:
    image: tomcat:7.0
    container_name: tomcat-server
    depends_on: 
      - database
    volumes:
      - ./release/modules/GKB/:/usr/local/gkb/modules/GKB
      - ./release/scripts/:/usr/local/bin/perl/scripts
    env_file:
      - .env

  apache-server:
    image: httpd:2.4
    container_name: apache-server
    volumes:
      - ./release/modules/GKB/:/usr/local/gkb/modules/GKB
      - ./release/scripts/:/usr/local/bin/perl/scripts

  database:
    image: mysql
    container_name: mysql-database
    volumes:
      - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    env_file:
      - .env