version: '3.2'
services:

  tomcat:
    image: reactome-tomcat
    container_name: tomcat-server
    hostname: tomcat-server
    build:
      context: ./tomcat
      dockerfile: tomcat.dockerfile
    depends_on:
      - mysql-for-tomcat
      - wordpress-sites
    links:
      - mysql-for-tomcat
      - wordpress-sites
    entrypoint: bash -c "/wait-for.sh mysql-for-tomcat:3306 -t 360 && /wait-for.sh wordpress-sites:80 -t 360 && catalina.sh run"
    volumes:
      - ./java-application-builder/webapps/ReactomeRESTfulAPI.war:/usr/local/tomcat/webapps/ReactomeRESTfulAPI.war #it  has been copied from feature/build-web-applications after building webapps
      - ./java-application-builder/webapps/PathwayBrowser.war:/usr/local/tomcat/webapps/PathwayBrowser.war
      - ./java-application-builder/webapps/analysis-service.war:/usr/local/tomcat/webapps/analysis-service.war
    #   - ./java-application-builder/webapps/ContentService.war:/usr/local/tomcat/webapps/ContentService.war
    #   - ./java-application-builder/webapps/content.war:/usr/local/tomcat/webapps/content.war
      - ./java-application-builder/downloads/interactors.db:/interactors.db
      - ./java-application-builder/downloads/analysis.bin:/analysis.bin
      - ./java-application-builder/downloads/diagrams_and_fireworks/fireworks:/usr/local/tomcat/webapps/download/current/fireworks
      - ./java-application-builder/downloads/diagrams_and_fireworks/diagram:/usr/local/tomcat/webapps/download/current/diagram
      - ./wait-for.sh:/wait-for.sh
      - ./tomcat/rewrite.config:/usr/local/tomcat/conf/Catalina/localhost/rewrite.config
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./tomcat/tomcat-server.xml:/usr/local/tomcat/conf/server.xml
      - ./tomcat/tomcat-manager.xml:/usr/local/tomcat/conf/Catalina/localhost/manager.xml
      - ./tomcat/analysis-service/results:/usr/local/AnalysisService/analysis-results
      - ./tomcat/analysis-service/reports:/usr/local/AnalysisService/analysis-reports
      - ./logs/applications/AnalysisService:/usr/local/AnalysisService/log
      - ./logs/applications/ContentService:/usr/local/search/log/content-service
      - ./logs/applications/DataContent:/usr/local/search/log/data-content
      - ./logs/tomcat/:/usr/local/tomcat/logs/ #to save logs inside host directory of tomcat/logs/
    env_file:
      - tomcat.env
    ports:
      - 8082:8080

  mysql-for-tomcat:
    image: mysql
    hostname: mysql-for-tomcat
    container_name: mysql-for-tomcat
    env_file:
      - tomcat.env
    volumes:
      - ./mysql/tomcat_data/:/docker-entrypoint-initdb.d
      - ./mysql/init.sh:/init.sh
      - ./logs/mysql/tomcat:/var/log/mysql
      - mysql-for-tomcat-log:/backup
    command: bash -c "/init.sh && exec /entrypoint.sh mysqld"

  mysql-database:
    image: mysql
    hostname: mysql-database
    container_name: mysql-database
    env_file:
      - wordpress.env
    volumes:
      - ./mysql/wordpress_data/:/docker-entrypoint-initdb.d
      - ./mysql/init.sh:/init.sh
      - ./logs/mysql/wordpress:/var/log/mysql
      - mysql-for-wordpress-log:/backup
    command: bash -c "/init.sh && exec /entrypoint.sh mysqld"


  wordpress-sites:
    hostname: wordpress-sites
    image: wordpress:4.8.1_for_reactome
    build:
      context: ./wordpress
      dockerfile: wordpress.dockerfile
    container_name: wordpress-sites
    links:
      - mysql-database
    depends_on:
      - mysql-database
    env_file:
      - wordpress.env
    ports:
      - 80:80
    entrypoint:  /wait-for.sh mysql-database:3306 -t 120  --  /usr/local/bin/docker-entrypoint.sh apache2-foreground
    volumes:
      - ./wordpress/wait-for.sh:/wait-for.sh
      - ./wordpress/htaccess:/var/www/html/.htaccess
      - ./wordpress/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./wordpress/header.php:/var/www/html/header.php
      - ./wordpress/footer.php:/var/www/html/footer.php
      - ./wordpress/Secrets.pm:/usr/local/gkb/modules/GKB/Secrets.pm
      - ./wordpress/cgi.load:/etc/apache2/mods-enabled/cgi.load
      - ./wordpress/proxy.load:/etc/apache2/mods-enabled/proxy.load
      - ./wordpress/proxy_http.load:/etc/apache2/mods-enabled/proxy_http.load
      - ./release/website/html/wordpress/wp-content/themes/HS_OICR_2013:/var/www/html/wp-content/themes/HS_OICR_2013
      - ./wordpress/curator-header.php:/var/www/html/wp-content/themes/HS_OICR_2013/header.php # Custom header just for Curator servers.
      - ./release/website/html/wordpress/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./release/website/cgi-bin:/usr/lib/cgi-bin
      - ./release/modules/GKB:/usr/local/gkb/modules/GKB
      - ./release/website/html/instructionlibrary.xml:/usr/local/gkb/website/html/instructionlibrary.xml
      - ./release/website/html/stylesheet.css:/var/www/html/stylesheet.css
      - ./release/website/html/stylesheets:/var/www/html/stylesheets
      - ./release/website/html/javascript:/var/www/html/javascript
      - ./release/website/html/icons:/var/www/html/icons
      - ./release/website/html/images:/var/www/html/images
      - ./release/website/html/xml:/var/www/html/xml
      - ./toc_files:/usr/local/gkb/website/html/img-fp/gk_current/:rw
      - ./tmp_files:/usr/local/gkb/website/html/img-tmp/:rw
      - ./logs/apache/:/var/log/apache2

volumes:
  mysql-for-wordpress-log:
  mysql-for-tomcat-log:
